import {
  SOCIAL_CATEGORY,
  ECONOMIC_CATEGORY,
  CONTEXT_CATEGORY,
  ECOLOGICAL_CATEGORY,
  INSTITUTIONAL_CATEGORY,
  getCategoryByID,
} from 'services/catalog';

export const DEFAULT_START_YEAR = 2006;
export const DEFAULT_END_YEAR = 2020;
